/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.json-view[_ngcontent-%COMP%] {\r\n  a {\r\n    cursor: pointer;\r\n    text-decoration: none;\r\n  }\r\n\r\n  .toggler {\r\n    width: 1em;\r\n    padding: 0;\r\n    display: block;\r\n    text-align: center;\r\n    float: left;\r\n  }\r\n\r\n  .collapse::before {\r\n    content: "-";\r\n  }\r\n\r\n  .expand::before {\r\n    content: "+";\r\n  }\r\n\r\n  .key {\r\n    color: #92278f;\r\n  }\r\n\r\n  .value {\r\n    color: #000000;\r\n\r\n    .string {\r\n      color: #3ab54a;\r\n    }\r\n\r\n    .number {\r\n      color: #25aae2;\r\n    }\r\n\r\n    .boolean {\r\n      color: #aa0d91;\r\n    }\r\n\r\n    .null {\r\n      color: #f1592a;\r\n    }\r\n  }\r\n\r\n  .children {\r\n    margin-left: 1em;\r\n  }\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiZTovcHJveWVjdHMvYW5ndWxhci9uZ3gtanNvbi12aWV3L3NyYy9uZ3gtanNvbi12aWV3L2NvbXBvbmVudC9qc29uLXZpZXcuY29tcG9uZW50LnNjc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vZTovcHJveWVjdHMvYW5ndWxhci9uZ3gtanNvbi12aWV3L3NyYy9uZ3gtanNvbi12aWV3L2NvbXBvbmVudC9qc29uLXZpZXcuY29tcG9uZW50LnNjc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
