/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './json-view.component.ngfactory';
import * as i2 from './json-view.component';
import * as i3 from './ngx-json-view.component';
const styles_NgxJsonViewComponent:any[] = ([] as any[]);
export const RenderType_NgxJsonViewComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_NgxJsonViewComponent,data:{}});
export function View_NgxJsonViewComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵeld(1,
      0,(null as any),(null as any),4,'div',[['class','ngx-json-view']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,
      (null as any),['\n      '])),(_l()(),i0.ɵeld(3,0,(null as any),(null as any),
      1,'json-view',[['class','json-view']],(null as any),(null as any),(null as any),
      i1.View_JsonViewComponent_0,i1.RenderType_JsonViewComponent)),i0.ɵdid(4,114688,
      (null as any),0,i2.JsonViewComponent,([] as any[]),{data:[0,'data'],level:[1,
          'level'],levelOpen:[2,'levelOpen']},(null as any)),(_l()(),i0.ɵted(-1,(null as any),
      ['\n    '])),(_l()(),i0.ɵted(-1,(null as any),['\n  ']))],(_ck,_v) => {
    var _co:i3.NgxJsonViewComponent = _v.component;
    const currVal_0:any = _co.data;
    const currVal_1:any = _co.level;
    const currVal_2:any = _co.levelOpen;
    _ck(_v,4,0,currVal_0,currVal_1,currVal_2);
  },(null as any));
}
export function View_NgxJsonViewComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'ngx-json-view',
      ([] as any[]),(null as any),(null as any),(null as any),View_NgxJsonViewComponent_0,
      RenderType_NgxJsonViewComponent)),i0.ɵdid(1,114688,(null as any),0,i3.NgxJsonViewComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const NgxJsonViewComponentNgFactory:i0.ComponentFactory<i3.NgxJsonViewComponent> = i0.ɵccf('ngx-json-view',
    i3.NgxJsonViewComponent,View_NgxJsonViewComponent_Host_0,{data:'data',levelOpen:'levelOpen'},
    {},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiZTovcHJveWVjdHMvYW5ndWxhci9uZ3gtanNvbi12aWV3L3NyYy9uZ3gtanNvbi12aWV3L2NvbXBvbmVudC9uZ3gtanNvbi12aWV3LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9lOi9wcm95ZWN0cy9hbmd1bGFyL25neC1qc29uLXZpZXcvc3JjL25neC1qc29uLXZpZXcvY29tcG9uZW50L25neC1qc29uLXZpZXcuY29tcG9uZW50LnRzIiwibmc6Ly8vZTovcHJveWVjdHMvYW5ndWxhci9uZ3gtanNvbi12aWV3L3NyYy9uZ3gtanNvbi12aWV3L2NvbXBvbmVudC9uZ3gtanNvbi12aWV3LmNvbXBvbmVudC50cy5OZ3hKc29uVmlld0NvbXBvbmVudC5odG1sIiwibmc6Ly8vZTovcHJveWVjdHMvYW5ndWxhci9uZ3gtanNvbi12aWV3L3NyYy9uZ3gtanNvbi12aWV3L2NvbXBvbmVudC9uZ3gtanNvbi12aWV3LmNvbXBvbmVudC50cy5OZ3hKc29uVmlld0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxkaXYgY2xhc3M9XCJuZ3gtanNvbi12aWV3XCI+XG4gICAgICA8anNvbi12aWV3IFtkYXRhXT1cImRhdGFcIiBbbGV2ZWxdPVwibGV2ZWxcIiBbbGV2ZWxPcGVuXT1cImxldmVsT3BlblwiIGNsYXNzPVwianNvbi12aWV3XCI+PC9qc29uLXZpZXc+XG4gICAgPC9kaXY+XG4gICIsIjxuZ3gtanNvbi12aWV3Pjwvbmd4LWpzb24tdmlldz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLDhDQUNJO01BQUE7TUFBQSwwREFBMkI7TUFBQSw2QkFDekI7TUFBQTtpRUFBQSxVQUFBO01BQUE7VUFBQSxtREFBK0Y7TUFBQSxhQUMzRjs7SUFETztJQUFjO0lBQWdCO0lBQXpDLFdBQVcsVUFBYyxVQUFnQixTQUF6Qzs7OztvQkNGTjtNQUFBO3FDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OzsifQ==
