/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ngx-json-view.module';
import * as i2 from '@angular/common';
export const NgxJsonViewModuleNgFactory:i0.NgModuleFactory<i1.NgxJsonViewModule> = i0.ɵcmf(i1.NgxJsonViewModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,i2.CommonModule,
          i2.CommonModule,([] as any[])),i0.ɵmpd(512,i1.NgxJsonViewModule,i1.NgxJsonViewModule,
          ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiZTovcHJveWVjdHMvYW5ndWxhci9uZ3gtanNvbi12aWV3L3NyYy9uZ3gtanNvbi12aWV3L25neC1qc29uLXZpZXcubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2U6L3Byb3llY3RzL2FuZ3VsYXIvbmd4LWpzb24tdmlldy9zcmMvbmd4LWpzb24tdmlldy9uZ3gtanNvbi12aWV3Lm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
